### ISSUE TITLE
Release version with Interputs changes support

### ISSUE THREAD

**Issue by szymonpk** [adafruit/Adafruit_ADXL343#2]
Hi,

I have noticed [HW Interputs examples](https://learn.adafruit.com/adxl343-breakout-learning-guide/hw-interrupts) aren't working with 1.0.1 library like described [here](https://learn.adafruit.com/adxl343-breakout-learning-guide/arduino).

I am getting the following error during compilation:

```
exit status 1
'class Adafruit_ADXL343' has no member named 'checkInterrupts'
```

Looks like there were changes made [after 1.0.1 release](https://github.com/adafruit/Adafruit_ADXL343/compare/1.0.1...master).

Can someone with proper permissions release new version and push it to libraries repository?

**Comment by ladyada** [comment]
@caternuson can u bump this library

**Comment by caternuson** [comment]
Done. Released as 1.1.0:
https://github.com/adafruit/Adafruit_ADXL343/releases/tag/1.1.0

@szymonpk Please try this latest release.

**Comment by szymonpk** [comment]
Now it is compiling just fine. Thank you :tada:
